### ISSUE TITLE
Update Cards

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/doc-ui#10]
```[tasklist]
## TODO
- [ ] Update CSS to include dynamic color options
- [ ] (Optional): Add icons
- [ ] (Optional): Introduce animation library (eye-catching)
```

```[tasklist]
## Icons
- [ ] Discuss addition of "icons" for recognizable components
- [ ] If icons, select library (proposals accepted)
```

**Comment by cstrangedk** [comment]
icon lib: https://phosphoricons.com/
